spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_manage?createDatabaseIfNotExist=true
    password: 1234@5
    username: root
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081